[features]
seeds = false
skip-lint = false
[programs.localnet]
my_shogi_nft = "EA7qTJVQeghgYfoFBNL9mAQNxXXvq8hrpHhsqsip1Kgg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
